window.esdocSearchIndex = [
  [
    "magister.js/src/absenceinfo.js~absenceinfo",
    "class/src/absenceInfo.js~AbsenceInfo.html",
    "<span>AbsenceInfo</span> <span class=\"search-result-import-path\">magister.js/src/absenceInfo.js</span>",
    "class"
  ],
  [
    "magister.js/src/activity.js~activity",
    "class/src/activity.js~Activity.html",
    "<span>Activity</span> <span class=\"search-result-import-path\">magister.js/src/activity.js</span>",
    "class"
  ],
  [
    "magister.js/src/activityelement.js~activityelement",
    "class/src/activityElement.js~ActivityElement.html",
    "<span>ActivityElement</span> <span class=\"search-result-import-path\">magister.js/src/activityElement.js</span>",
    "class"
  ],
  [
    "magister.js/src/addressinfo.js~addressinfo",
    "class/src/addressInfo.js~AddressInfo.html",
    "<span>AddressInfo</span> <span class=\"search-result-import-path\">magister.js/src/addressInfo.js</span>",
    "class"
  ],
  [
    "magister.js/src/appointment.js~appointment",
    "class/src/appointment.js~Appointment.html",
    "<span>Appointment</span> <span class=\"search-result-import-path\">magister.js/src/appointment.js</span>",
    "class"
  ],
  [
    "magister.js/src/assignment.js~assignment",
    "class/src/assignment.js~Assignment.html",
    "<span>Assignment</span> <span class=\"search-result-import-path\">magister.js/src/assignment.js</span>",
    "class"
  ],
  [
    "magister.js/src/assignmentversion.js~assignmentversion",
    "class/src/assignmentVersion.js~AssignmentVersion.html",
    "<span>AssignmentVersion</span> <span class=\"search-result-import-path\">magister.js/src/assignmentVersion.js</span>",
    "class"
  ],
  [
    "magister.js/src/autherror.js~autherror",
    "class/src/authError.js~AuthError.html",
    "<span>AuthError</span> <span class=\"search-result-import-path\">magister.js/src/authError.js</span>",
    "class"
  ],
  [
    "magister.js/src/class.js~class",
    "class/src/class.js~Class.html",
    "<span>Class</span> <span class=\"search-result-import-path\">magister.js/src/class.js</span>",
    "class"
  ],
  [
    "magister.js/src/course.js~course",
    "class/src/course.js~Course.html",
    "<span>Course</span> <span class=\"search-result-import-path\">magister.js/src/course.js</span>",
    "class"
  ],
  [
    "magister.js/src/file.js~file",
    "class/src/file.js~File.html",
    "<span>File</span> <span class=\"search-result-import-path\">magister.js/src/file.js</span>",
    "class"
  ],
  [
    "magister.js/src/filefolder.js~filefolder",
    "class/src/fileFolder.js~FileFolder.html",
    "<span>FileFolder</span> <span class=\"search-result-import-path\">magister.js/src/fileFolder.js</span>",
    "class"
  ],
  [
    "magister.js/src/grade.js~grade",
    "class/src/grade.js~Grade.html",
    "<span>Grade</span> <span class=\"search-result-import-path\">magister.js/src/grade.js</span>",
    "class"
  ],
  [
    "magister.js/src/gradeperiod.js~gradeperiod",
    "class/src/gradePeriod.js~GradePeriod.html",
    "<span>GradePeriod</span> <span class=\"search-result-import-path\">magister.js/src/gradePeriod.js</span>",
    "class"
  ],
  [
    "magister.js/src/gradetype.js~gradetype",
    "class/src/gradeType.js~GradeType.html",
    "<span>GradeType</span> <span class=\"search-result-import-path\">magister.js/src/gradeType.js</span>",
    "class"
  ],
  [
    "magister.js/src/magister.js~magister",
    "class/src/magister.js~Magister.html",
    "<span>Magister</span> <span class=\"search-result-import-path\">magister.js/src/magister.js</span>",
    "class"
  ],
  [
    "magister.js/src/magistererror.js~magistererror",
    "class/src/magisterError.js~MagisterError.html",
    "<span>MagisterError</span> <span class=\"search-result-import-path\">magister.js/src/magisterError.js</span>",
    "class"
  ],
  [
    "magister.js/src/message.js~message",
    "class/src/message.js~Message.html",
    "<span>Message</span> <span class=\"search-result-import-path\">magister.js/src/message.js</span>",
    "class"
  ],
  [
    "magister.js/src/messagefolder.js~messagefolder",
    "class/src/messageFolder.js~MessageFolder.html",
    "<span>MessageFolder</span> <span class=\"search-result-import-path\">magister.js/src/messageFolder.js</span>",
    "class"
  ],
  [
    "magister.js/src/person.js~person",
    "class/src/person.js~Person.html",
    "<span>Person</span> <span class=\"search-result-import-path\">magister.js/src/person.js</span>",
    "class"
  ],
  [
    "magister.js/src/profileinfo.js~profileinfo",
    "class/src/profileInfo.js~ProfileInfo.html",
    "<span>ProfileInfo</span> <span class=\"search-result-import-path\">magister.js/src/profileInfo.js</span>",
    "class"
  ],
  [
    "magister.js/src/profilesettings.js~profilesettings",
    "class/src/profileSettings.js~ProfileSettings.html",
    "<span>ProfileSettings</span> <span class=\"search-result-import-path\">magister.js/src/profileSettings.js</span>",
    "class"
  ],
  [
    "magister.js/src/school.js~school",
    "class/src/school.js~School.html",
    "<span>School</span> <span class=\"search-result-import-path\">magister.js/src/school.js</span>",
    "class"
  ],
  [
    "magister.js/src/schoolutility.js~schoolutility",
    "class/src/schoolUtility.js~SchoolUtility.html",
    "<span>SchoolUtility</span> <span class=\"search-result-import-path\">magister.js/src/schoolUtility.js</span>",
    "class"
  ],
  [
    "magister.js/src/magister.js~version",
    "variable/index.html#static-variable-VERSION",
    "<span>VERSION</span> <span class=\"search-result-import-path\">magister.js/src/magister.js</span>",
    "variable"
  ],
  [
    "magister.js/src/versioninfo.js~versioninfo",
    "class/src/versionInfo.js~VersionInfo.html",
    "<span>VersionInfo</span> <span class=\"search-result-import-path\">magister.js/src/versionInfo.js</span>",
    "class"
  ],
  [
    "magister.js/src/magister.js~getschools",
    "function/index.html#static-function-getSchools",
    "<span>getSchools</span> <span class=\"search-result-import-path\">magister.js/src/magister.js</span>",
    "function"
  ],
  [
    "magister.js/src/magister.js~magister",
    "function/index.html#static-function-magister",
    "<span>magister</span> <span class=\"search-result-import-path\">magister.js/src/magister.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/absenceinfo.js",
    "file/src/absenceInfo.js.html",
    "src/absenceInfo.js",
    "file"
  ],
  [
    "src/absenceinfo.js~absenceinfo#appointment",
    "class/src/absenceInfo.js~AbsenceInfo.html#instance-member-appointment",
    "src/absenceInfo.js~AbsenceInfo#appointment",
    "member"
  ],
  [
    "src/absenceinfo.js~absenceinfo#begin",
    "class/src/absenceInfo.js~AbsenceInfo.html#instance-member-begin",
    "src/absenceInfo.js~AbsenceInfo#begin",
    "member"
  ],
  [
    "src/absenceinfo.js~absenceinfo#code",
    "class/src/absenceInfo.js~AbsenceInfo.html#instance-member-code",
    "src/absenceInfo.js~AbsenceInfo#code",
    "member"
  ],
  [
    "src/absenceinfo.js~absenceinfo#description",
    "class/src/absenceInfo.js~AbsenceInfo.html#instance-member-description",
    "src/absenceInfo.js~AbsenceInfo#description",
    "member"
  ],
  [
    "src/absenceinfo.js~absenceinfo#end",
    "class/src/absenceInfo.js~AbsenceInfo.html#instance-member-end",
    "src/absenceInfo.js~AbsenceInfo#end",
    "member"
  ],
  [
    "src/absenceinfo.js~absenceinfo#id",
    "class/src/absenceInfo.js~AbsenceInfo.html#instance-member-id",
    "src/absenceInfo.js~AbsenceInfo#id",
    "member"
  ],
  [
    "src/absenceinfo.js~absenceinfo#ispermitted",
    "class/src/absenceInfo.js~AbsenceInfo.html#instance-member-isPermitted",
    "src/absenceInfo.js~AbsenceInfo#isPermitted",
    "member"
  ],
  [
    "src/absenceinfo.js~absenceinfo#schoolhour",
    "class/src/absenceInfo.js~AbsenceInfo.html#instance-member-schoolHour",
    "src/absenceInfo.js~AbsenceInfo#schoolHour",
    "member"
  ],
  [
    "src/absenceinfo.js~absenceinfo#type",
    "class/src/absenceInfo.js~AbsenceInfo.html#instance-get-type",
    "src/absenceInfo.js~AbsenceInfo#type",
    "member"
  ],
  [
    "src/activity.js",
    "file/src/activity.js.html",
    "src/activity.js",
    "file"
  ],
  [
    "src/activity.js~activity#description",
    "class/src/activity.js~Activity.html#instance-member-description",
    "src/activity.js~Activity#description",
    "member"
  ],
  [
    "src/activity.js~activity#elements",
    "class/src/activity.js~Activity.html#instance-method-elements",
    "src/activity.js~Activity#elements",
    "method"
  ],
  [
    "src/activity.js~activity#id",
    "class/src/activity.js~Activity.html#instance-member-id",
    "src/activity.js~Activity#id",
    "member"
  ],
  [
    "src/activity.js~activity#signinend",
    "class/src/activity.js~Activity.html#instance-member-signinEnd",
    "src/activity.js~Activity#signinEnd",
    "member"
  ],
  [
    "src/activity.js~activity#signinstart",
    "class/src/activity.js~Activity.html#instance-member-signinStart",
    "src/activity.js~Activity#signinStart",
    "member"
  ],
  [
    "src/activity.js~activity#title",
    "class/src/activity.js~Activity.html#instance-member-title",
    "src/activity.js~Activity#title",
    "member"
  ],
  [
    "src/activity.js~activity#visiblefrom",
    "class/src/activity.js~Activity.html#instance-member-visibleFrom",
    "src/activity.js~Activity#visibleFrom",
    "member"
  ],
  [
    "src/activity.js~activity#visibleto",
    "class/src/activity.js~Activity.html#instance-member-visibleTo",
    "src/activity.js~Activity#visibleTo",
    "member"
  ],
  [
    "src/activityelement.js",
    "file/src/activityElement.js.html",
    "src/activityElement.js",
    "file"
  ],
  [
    "src/activityelement.js~activityelement#abletosignup",
    "class/src/activityElement.js~ActivityElement.html#instance-member-ableToSignup",
    "src/activityElement.js~ActivityElement#ableToSignup",
    "member"
  ],
  [
    "src/activityelement.js~activityelement#activityid",
    "class/src/activityElement.js~ActivityElement.html#instance-member-activityId",
    "src/activityElement.js~ActivityElement#activityId",
    "member"
  ],
  [
    "src/activityelement.js~activityelement#attachments",
    "class/src/activityElement.js~ActivityElement.html#instance-member-attachments",
    "src/activityElement.js~ActivityElement#attachments",
    "member"
  ],
  [
    "src/activityelement.js~activityelement#description",
    "class/src/activityElement.js~ActivityElement.html#instance-member-description",
    "src/activityElement.js~ActivityElement#description",
    "member"
  ],
  [
    "src/activityelement.js~activityelement#id",
    "class/src/activityElement.js~ActivityElement.html#instance-member-id",
    "src/activityElement.js~ActivityElement#id",
    "member"
  ],
  [
    "src/activityelement.js~activityelement#mandatorilysignedup",
    "class/src/activityElement.js~ActivityElement.html#instance-member-mandatorilySignedup",
    "src/activityElement.js~ActivityElement#mandatorilySignedup",
    "member"
  ],
  [
    "src/activityelement.js~activityelement#maxparticipants",
    "class/src/activityElement.js~ActivityElement.html#instance-member-maxParticipants",
    "src/activityElement.js~ActivityElement#maxParticipants",
    "member"
  ],
  [
    "src/activityelement.js~activityelement#minparticipants",
    "class/src/activityElement.js~ActivityElement.html#instance-member-minParticipants",
    "src/activityElement.js~ActivityElement#minParticipants",
    "member"
  ],
  [
    "src/activityelement.js~activityelement#placesleft",
    "class/src/activityElement.js~ActivityElement.html#instance-member-placesLeft",
    "src/activityElement.js~ActivityElement#placesLeft",
    "member"
  ],
  [
    "src/activityelement.js~activityelement#signedup",
    "class/src/activityElement.js~ActivityElement.html#instance-member-signedup",
    "src/activityElement.js~ActivityElement#signedup",
    "member"
  ],
  [
    "src/activityelement.js~activityelement#signinend",
    "class/src/activityElement.js~ActivityElement.html#instance-member-signinEnd",
    "src/activityElement.js~ActivityElement#signinEnd",
    "member"
  ],
  [
    "src/activityelement.js~activityelement#signinstart",
    "class/src/activityElement.js~ActivityElement.html#instance-member-signinStart",
    "src/activityElement.js~ActivityElement#signinStart",
    "member"
  ],
  [
    "src/activityelement.js~activityelement#signup",
    "class/src/activityElement.js~ActivityElement.html#instance-method-signup",
    "src/activityElement.js~ActivityElement#signup",
    "method"
  ],
  [
    "src/activityelement.js~activityelement#title",
    "class/src/activityElement.js~ActivityElement.html#instance-member-title",
    "src/activityElement.js~ActivityElement#title",
    "member"
  ],
  [
    "src/addressinfo.js",
    "file/src/addressInfo.js.html",
    "src/addressInfo.js",
    "file"
  ],
  [
    "src/addressinfo.js~addressinfo#city",
    "class/src/addressInfo.js~AddressInfo.html#instance-member-city",
    "src/addressInfo.js~AddressInfo#city",
    "member"
  ],
  [
    "src/addressinfo.js~addressinfo#housenumber",
    "class/src/addressInfo.js~AddressInfo.html#instance-member-houseNumber",
    "src/addressInfo.js~AddressInfo#houseNumber",
    "member"
  ],
  [
    "src/addressinfo.js~addressinfo#postalcode",
    "class/src/addressInfo.js~AddressInfo.html#instance-member-postalCode",
    "src/addressInfo.js~AddressInfo#postalCode",
    "member"
  ],
  [
    "src/addressinfo.js~addressinfo#street",
    "class/src/addressInfo.js~AddressInfo.html#instance-member-street",
    "src/addressInfo.js~AddressInfo#street",
    "member"
  ],
  [
    "src/addressinfo.js~addressinfo#suffix",
    "class/src/addressInfo.js~AddressInfo.html#instance-member-suffix",
    "src/addressInfo.js~AddressInfo#suffix",
    "member"
  ],
  [
    "src/appointment.js",
    "file/src/appointment.js.html",
    "src/appointment.js",
    "file"
  ],
  [
    "src/appointment.js~appointment#absenceinfo",
    "class/src/appointment.js~Appointment.html#instance-member-absenceInfo",
    "src/appointment.js~Appointment#absenceInfo",
    "member"
  ],
  [
    "src/appointment.js~appointment#annotation",
    "class/src/appointment.js~Appointment.html#instance-member-annotation",
    "src/appointment.js~Appointment#annotation",
    "member"
  ],
  [
    "src/appointment.js~appointment#appointmentid",
    "class/src/appointment.js~Appointment.html#instance-member-appointmentId",
    "src/appointment.js~Appointment#appointmentId",
    "member"
  ],
  [
    "src/appointment.js~appointment#attachments",
    "class/src/appointment.js~Appointment.html#instance-method-attachments",
    "src/appointment.js~Appointment#attachments",
    "method"
  ],
  [
    "src/appointment.js~appointment#classrooms",
    "class/src/appointment.js~Appointment.html#instance-member-classRooms",
    "src/appointment.js~Appointment#classRooms",
    "member"
  ],
  [
    "src/appointment.js~appointment#classes",
    "class/src/appointment.js~Appointment.html#instance-member-classes",
    "src/appointment.js~Appointment#classes",
    "member"
  ],
  [
    "src/appointment.js~appointment#content",
    "class/src/appointment.js~Appointment.html#instance-member-content",
    "src/appointment.js~Appointment#content",
    "member"
  ],
  [
    "src/appointment.js~appointment#description",
    "class/src/appointment.js~Appointment.html#instance-member-description",
    "src/appointment.js~Appointment#description",
    "member"
  ],
  [
    "src/appointment.js~appointment#displaytype",
    "class/src/appointment.js~Appointment.html#instance-member-displayType",
    "src/appointment.js~Appointment#displayType",
    "member"
  ],
  [
    "src/appointment.js~appointment#end",
    "class/src/appointment.js~Appointment.html#instance-member-end",
    "src/appointment.js~Appointment#end",
    "member"
  ],
  [
    "src/appointment.js~appointment#endbyschoolhour",
    "class/src/appointment.js~Appointment.html#instance-member-endBySchoolhour",
    "src/appointment.js~Appointment#endBySchoolhour",
    "member"
  ],
  [
    "src/appointment.js~appointment#groups",
    "class/src/appointment.js~Appointment.html#instance-member-groups",
    "src/appointment.js~Appointment#groups",
    "member"
  ],
  [
    "src/appointment.js~appointment#hasattachments",
    "class/src/appointment.js~Appointment.html#instance-member-hasAttachments",
    "src/appointment.js~Appointment#hasAttachments",
    "member"
  ],
  [
    "src/appointment.js~appointment#id",
    "class/src/appointment.js~Appointment.html#instance-member-id",
    "src/appointment.js~Appointment#id",
    "member"
  ],
  [
    "src/appointment.js~appointment#infotype",
    "class/src/appointment.js~Appointment.html#instance-member-infoType",
    "src/appointment.js~Appointment#infoType",
    "member"
  ],
  [
    "src/appointment.js~appointment#iscancelled",
    "class/src/appointment.js~Appointment.html#instance-member-isCancelled",
    "src/appointment.js~Appointment#isCancelled",
    "member"
  ],
  [
    "src/appointment.js~appointment#ischanged",
    "class/src/appointment.js~Appointment.html#instance-member-isChanged",
    "src/appointment.js~Appointment#isChanged",
    "member"
  ],
  [
    "src/appointment.js~appointment#isdone",
    "class/src/appointment.js~Appointment.html#instance-member-isDone",
    "src/appointment.js~Appointment#isDone",
    "member"
  ],
  [
    "src/appointment.js~appointment#isfullday",
    "class/src/appointment.js~Appointment.html#instance-member-isFullDay",
    "src/appointment.js~Appointment#isFullDay",
    "member"
  ],
  [
    "src/appointment.js~appointment#location",
    "class/src/appointment.js~Appointment.html#instance-member-location",
    "src/appointment.js~Appointment#location",
    "member"
  ],
  [
    "src/appointment.js~appointment#remove",
    "class/src/appointment.js~Appointment.html#instance-method-remove",
    "src/appointment.js~Appointment#remove",
    "method"
  ],
  [
    "src/appointment.js~appointment#savechanges",
    "class/src/appointment.js~Appointment.html#instance-method-saveChanges",
    "src/appointment.js~Appointment#saveChanges",
    "method"
  ],
  [
    "src/appointment.js~appointment#start",
    "class/src/appointment.js~Appointment.html#instance-member-start",
    "src/appointment.js~Appointment#start",
    "member"
  ],
  [
    "src/appointment.js~appointment#startbyschoolhour",
    "class/src/appointment.js~Appointment.html#instance-member-startBySchoolhour",
    "src/appointment.js~Appointment#startBySchoolhour",
    "member"
  ],
  [
    "src/appointment.js~appointment#status",
    "class/src/appointment.js~Appointment.html#instance-member-status",
    "src/appointment.js~Appointment#status",
    "member"
  ],
  [
    "src/appointment.js~appointment#teachers",
    "class/src/appointment.js~Appointment.html#instance-member-teachers",
    "src/appointment.js~Appointment#teachers",
    "member"
  ],
  [
    "src/appointment.js~appointment#type",
    "class/src/appointment.js~Appointment.html#instance-member-type",
    "src/appointment.js~Appointment#type",
    "member"
  ],
  [
    "src/assignment.js",
    "file/src/assignment.js.html",
    "src/assignment.js",
    "file"
  ],
  [
    "src/assignment.js~assignment#canhandin",
    "class/src/assignment.js~Assignment.html#instance-member-canHandIn",
    "src/assignment.js~Assignment#canHandIn",
    "member"
  ],
  [
    "src/assignment.js~assignment#class",
    "class/src/assignment.js~Assignment.html#instance-member-class",
    "src/assignment.js~Assignment#class",
    "member"
  ],
  [
    "src/assignment.js~assignment#deadline",
    "class/src/assignment.js~Assignment.html#instance-member-deadline",
    "src/assignment.js~Assignment#deadline",
    "member"
  ],
  [
    "src/assignment.js~assignment#description",
    "class/src/assignment.js~Assignment.html#instance-member-description",
    "src/assignment.js~Assignment#description",
    "member"
  ],
  [
    "src/assignment.js~assignment#files",
    "class/src/assignment.js~Assignment.html#instance-member-files",
    "src/assignment.js~Assignment#files",
    "member"
  ],
  [
    "src/assignment.js~assignment#finished",
    "class/src/assignment.js~Assignment.html#instance-member-finished",
    "src/assignment.js~Assignment#finished",
    "member"
  ],
  [
    "src/assignment.js~assignment#grade",
    "class/src/assignment.js~Assignment.html#instance-member-grade",
    "src/assignment.js~Assignment#grade",
    "member"
  ],
  [
    "src/assignment.js~assignment#handinagain",
    "class/src/assignment.js~Assignment.html#instance-member-handInAgain",
    "src/assignment.js~Assignment#handInAgain",
    "member"
  ],
  [
    "src/assignment.js~assignment#handedinon",
    "class/src/assignment.js~Assignment.html#instance-member-handedInOn",
    "src/assignment.js~Assignment#handedInOn",
    "member"
  ],
  [
    "src/assignment.js~assignment#id",
    "class/src/assignment.js~Assignment.html#instance-member-id",
    "src/assignment.js~Assignment#id",
    "member"
  ],
  [
    "src/assignment.js~assignment#markedon",
    "class/src/assignment.js~Assignment.html#instance-member-markedOn",
    "src/assignment.js~Assignment#markedOn",
    "member"
  ],
  [
    "src/assignment.js~assignment#name",
    "class/src/assignment.js~Assignment.html#instance-member-name",
    "src/assignment.js~Assignment#name",
    "member"
  ],
  [
    "src/assignment.js~assignment#teachers",
    "class/src/assignment.js~Assignment.html#instance-member-teachers",
    "src/assignment.js~Assignment#teachers",
    "member"
  ],
  [
    "src/assignment.js~assignment#versionids",
    "class/src/assignment.js~Assignment.html#instance-member-versionIds",
    "src/assignment.js~Assignment#versionIds",
    "member"
  ],
  [
    "src/assignment.js~assignment#versions",
    "class/src/assignment.js~Assignment.html#instance-method-versions",
    "src/assignment.js~Assignment#versions",
    "method"
  ],
  [
    "src/assignmentversion.js",
    "file/src/assignmentVersion.js.html",
    "src/assignmentVersion.js",
    "file"
  ],
  [
    "src/assignmentversion.js~assignmentversion#deadline",
    "class/src/assignmentVersion.js~AssignmentVersion.html#instance-member-deadline",
    "src/assignmentVersion.js~AssignmentVersion#deadline",
    "member"
  ],
  [
    "src/assignmentversion.js~assignmentversion#feedbackfiles",
    "class/src/assignmentVersion.js~AssignmentVersion.html#instance-member-feedbackFiles",
    "src/assignmentVersion.js~AssignmentVersion#feedbackFiles",
    "member"
  ],
  [
    "src/assignmentversion.js~assignmentversion#grade",
    "class/src/assignmentVersion.js~AssignmentVersion.html#instance-member-grade",
    "src/assignmentVersion.js~AssignmentVersion#grade",
    "member"
  ],
  [
    "src/assignmentversion.js~assignmentversion#handedinfiles",
    "class/src/assignmentVersion.js~AssignmentVersion.html#instance-member-handedInFiles",
    "src/assignmentVersion.js~AssignmentVersion#handedInFiles",
    "member"
  ],
  [
    "src/assignmentversion.js~assignmentversion#handedinon",
    "class/src/assignmentVersion.js~AssignmentVersion.html#instance-member-handedInOn",
    "src/assignmentVersion.js~AssignmentVersion#handedInOn",
    "member"
  ],
  [
    "src/assignmentversion.js~assignmentversion#id",
    "class/src/assignmentVersion.js~AssignmentVersion.html#instance-member-id",
    "src/assignmentVersion.js~AssignmentVersion#id",
    "member"
  ],
  [
    "src/assignmentversion.js~assignmentversion#markedon",
    "class/src/assignmentVersion.js~AssignmentVersion.html#instance-member-markedOn",
    "src/assignmentVersion.js~AssignmentVersion#markedOn",
    "member"
  ],
  [
    "src/assignmentversion.js~assignmentversion#pupilmessage",
    "class/src/assignmentVersion.js~AssignmentVersion.html#instance-member-pupilMessage",
    "src/assignmentVersion.js~AssignmentVersion#pupilMessage",
    "member"
  ],
  [
    "src/assignmentversion.js~assignmentversion#state",
    "class/src/assignmentVersion.js~AssignmentVersion.html#instance-member-state",
    "src/assignmentVersion.js~AssignmentVersion#state",
    "member"
  ],
  [
    "src/assignmentversion.js~assignmentversion#teachernotice",
    "class/src/assignmentVersion.js~AssignmentVersion.html#instance-member-teacherNotice",
    "src/assignmentVersion.js~AssignmentVersion#teacherNotice",
    "member"
  ],
  [
    "src/assignmentversion.js~assignmentversion#toolate",
    "class/src/assignmentVersion.js~AssignmentVersion.html#instance-member-tooLate",
    "src/assignmentVersion.js~AssignmentVersion#tooLate",
    "member"
  ],
  [
    "src/assignmentversion.js~assignmentversion#version",
    "class/src/assignmentVersion.js~AssignmentVersion.html#instance-member-version",
    "src/assignmentVersion.js~AssignmentVersion#version",
    "member"
  ],
  [
    "src/autherror.js",
    "file/src/authError.js.html",
    "src/authError.js",
    "file"
  ],
  [
    "src/autherror.js~autherror#tostring",
    "class/src/authError.js~AuthError.html#instance-method-toString",
    "src/authError.js~AuthError#toString",
    "method"
  ],
  [
    "src/class.js",
    "file/src/class.js.html",
    "src/class.js",
    "file"
  ],
  [
    "src/class.js~class#abbreviation",
    "class/src/class.js~Class.html#instance-member-abbreviation",
    "src/class.js~Class#abbreviation",
    "member"
  ],
  [
    "src/class.js~class#begindate",
    "class/src/class.js~Class.html#instance-member-beginDate",
    "src/class.js~Class#beginDate",
    "member"
  ],
  [
    "src/class.js~class#description",
    "class/src/class.js~Class.html#instance-member-description",
    "src/class.js~Class#description",
    "member"
  ],
  [
    "src/class.js~class#enddate",
    "class/src/class.js~Class.html#instance-member-endDate",
    "src/class.js~Class#endDate",
    "member"
  ],
  [
    "src/class.js~class#hasclassexemption",
    "class/src/class.js~Class.html#instance-member-hasClassExemption",
    "src/class.js~Class#hasClassExemption",
    "member"
  ],
  [
    "src/class.js~class#id",
    "class/src/class.js~Class.html#instance-member-id",
    "src/class.js~Class#id",
    "member"
  ],
  [
    "src/class.js~class#number",
    "class/src/class.js~Class.html#instance-member-number",
    "src/class.js~Class#number",
    "member"
  ],
  [
    "src/class.js~class#teacher",
    "class/src/class.js~Class.html#instance-member-teacher",
    "src/class.js~Class#teacher",
    "member"
  ],
  [
    "src/course.js",
    "file/src/course.js.html",
    "src/course.js",
    "file"
  ],
  [
    "src/course.js~course#classes",
    "class/src/course.js~Course.html#instance-method-classes",
    "src/course.js~Course#classes",
    "method"
  ],
  [
    "src/course.js~course#current",
    "class/src/course.js~Course.html#instance-get-current",
    "src/course.js~Course#current",
    "member"
  ],
  [
    "src/course.js~course#curricula",
    "class/src/course.js~Course.html#instance-member-curricula",
    "src/course.js~Course#curricula",
    "member"
  ],
  [
    "src/course.js~course#end",
    "class/src/course.js~Course.html#instance-member-end",
    "src/course.js~Course#end",
    "member"
  ],
  [
    "src/course.js~course#grades",
    "class/src/course.js~Course.html#instance-method-grades",
    "src/course.js~Course#grades",
    "method"
  ],
  [
    "src/course.js~course#group",
    "class/src/course.js~Course.html#instance-member-group",
    "src/course.js~Course#group",
    "member"
  ],
  [
    "src/course.js~course#id",
    "class/src/course.js~Course.html#instance-member-id",
    "src/course.js~Course#id",
    "member"
  ],
  [
    "src/course.js~course#schoolperiod",
    "class/src/course.js~Course.html#instance-member-schoolPeriod",
    "src/course.js~Course#schoolPeriod",
    "member"
  ],
  [
    "src/course.js~course#start",
    "class/src/course.js~Course.html#instance-member-start",
    "src/course.js~Course#start",
    "member"
  ],
  [
    "src/course.js~course#type",
    "class/src/course.js~Course.html#instance-member-type",
    "src/course.js~Course#type",
    "member"
  ],
  [
    "src/file.js",
    "file/src/file.js.html",
    "src/file.js",
    "file"
  ],
  [
    "src/file.js~file#addedby",
    "class/src/file.js~File.html#instance-member-addedBy",
    "src/file.js~File#addedBy",
    "member"
  ],
  [
    "src/file.js~file#changeddate",
    "class/src/file.js~File.html#instance-member-changedDate",
    "src/file.js~File#changedDate",
    "member"
  ],
  [
    "src/file.js~file#creationdate",
    "class/src/file.js~File.html#instance-member-creationDate",
    "src/file.js~File#creationDate",
    "member"
  ],
  [
    "src/file.js~file#download",
    "class/src/file.js~File.html#instance-method-download",
    "src/file.js~File#download",
    "method"
  ],
  [
    "src/file.js~file#fileblobid",
    "class/src/file.js~File.html#instance-member-fileBlobId",
    "src/file.js~File#fileBlobId",
    "member"
  ],
  [
    "src/file.js~file#filefolder",
    "class/src/file.js~File.html#instance-member-fileFolder",
    "src/file.js~File#fileFolder",
    "member"
  ],
  [
    "src/file.js~file#id",
    "class/src/file.js~File.html#instance-member-id",
    "src/file.js~File#id",
    "member"
  ],
  [
    "src/file.js~file#mime",
    "class/src/file.js~File.html#instance-member-mime",
    "src/file.js~File#mime",
    "member"
  ],
  [
    "src/file.js~file#name",
    "class/src/file.js~File.html#instance-member-name",
    "src/file.js~File#name",
    "member"
  ],
  [
    "src/file.js~file#referenceid",
    "class/src/file.js~File.html#instance-member-referenceId",
    "src/file.js~File#referenceId",
    "member"
  ],
  [
    "src/file.js~file#remove",
    "class/src/file.js~File.html#instance-method-remove",
    "src/file.js~File#remove",
    "method"
  ],
  [
    "src/file.js~file#rights",
    "class/src/file.js~File.html#instance-member-rights",
    "src/file.js~File#rights",
    "member"
  ],
  [
    "src/file.js~file#savechanges",
    "class/src/file.js~File.html#instance-method-saveChanges",
    "src/file.js~File#saveChanges",
    "method"
  ],
  [
    "src/file.js~file#size",
    "class/src/file.js~File.html#instance-member-size",
    "src/file.js~File#size",
    "member"
  ],
  [
    "src/file.js~file#type",
    "class/src/file.js~File.html#instance-member-type",
    "src/file.js~File#type",
    "member"
  ],
  [
    "src/file.js~file#uniqueid",
    "class/src/file.js~File.html#instance-member-uniqueId",
    "src/file.js~File#uniqueId",
    "member"
  ],
  [
    "src/file.js~file#uri",
    "class/src/file.js~File.html#instance-member-uri",
    "src/file.js~File#uri",
    "member"
  ],
  [
    "src/filefolder.js",
    "file/src/fileFolder.js.html",
    "src/fileFolder.js",
    "file"
  ],
  [
    "src/filefolder.js~filefolder#files",
    "class/src/fileFolder.js~FileFolder.html#instance-method-files",
    "src/fileFolder.js~FileFolder#files",
    "method"
  ],
  [
    "src/filefolder.js~filefolder#id",
    "class/src/fileFolder.js~FileFolder.html#instance-member-id",
    "src/fileFolder.js~FileFolder#id",
    "member"
  ],
  [
    "src/filefolder.js~filefolder#name",
    "class/src/fileFolder.js~FileFolder.html#instance-member-name",
    "src/fileFolder.js~FileFolder#name",
    "member"
  ],
  [
    "src/filefolder.js~filefolder#parentid",
    "class/src/fileFolder.js~FileFolder.html#instance-member-parentId",
    "src/fileFolder.js~FileFolder#parentId",
    "member"
  ],
  [
    "src/filefolder.js~filefolder#rights",
    "class/src/fileFolder.js~FileFolder.html#instance-member-rights",
    "src/fileFolder.js~FileFolder#rights",
    "member"
  ],
  [
    "src/grade.js",
    "file/src/grade.js.html",
    "src/grade.js",
    "file"
  ],
  [
    "src/grade.js~grade#assignmentid",
    "class/src/grade.js~Grade.html#instance-member-assignmentId",
    "src/grade.js~Grade#assignmentId",
    "member"
  ],
  [
    "src/grade.js~grade#atlaterdate",
    "class/src/grade.js~Grade.html#instance-member-atLaterDate",
    "src/grade.js~Grade#atLaterDate",
    "member"
  ],
  [
    "src/grade.js~grade#class",
    "class/src/grade.js~Grade.html#instance-member-class",
    "src/grade.js~Grade#class",
    "member"
  ],
  [
    "src/grade.js~grade#classexemption",
    "class/src/grade.js~Grade.html#instance-member-classExemption",
    "src/grade.js~Grade#classExemption",
    "member"
  ],
  [
    "src/grade.js~grade#counts",
    "class/src/grade.js~Grade.html#instance-member-counts",
    "src/grade.js~Grade#counts",
    "member"
  ],
  [
    "src/grade.js~grade#datefilledin",
    "class/src/grade.js~Grade.html#instance-member-dateFilledIn",
    "src/grade.js~Grade#dateFilledIn",
    "member"
  ],
  [
    "src/grade.js~grade#description",
    "class/src/grade.js~Grade.html#instance-member-description",
    "src/grade.js~Grade#description",
    "member"
  ],
  [
    "src/grade.js~grade#exemption",
    "class/src/grade.js~Grade.html#instance-member-exemption",
    "src/grade.js~Grade#exemption",
    "member"
  ],
  [
    "src/grade.js~grade#fill",
    "class/src/grade.js~Grade.html#instance-method-fill",
    "src/grade.js~Grade#fill",
    "method"
  ],
  [
    "src/grade.js~grade#filled",
    "class/src/grade.js~Grade.html#instance-member-filled",
    "src/grade.js~Grade#filled",
    "member"
  ],
  [
    "src/grade.js~grade#grade",
    "class/src/grade.js~Grade.html#instance-member-grade",
    "src/grade.js~Grade#grade",
    "member"
  ],
  [
    "src/grade.js~grade#id",
    "class/src/grade.js~Grade.html#instance-member-id",
    "src/grade.js~Grade#id",
    "member"
  ],
  [
    "src/grade.js~grade#passed",
    "class/src/grade.js~Grade.html#instance-member-passed",
    "src/grade.js~Grade#passed",
    "member"
  ],
  [
    "src/grade.js~grade#period",
    "class/src/grade.js~Grade.html#instance-member-period",
    "src/grade.js~Grade#period",
    "member"
  ],
  [
    "src/grade.js~grade#teacher",
    "class/src/grade.js~Grade.html#instance-member-teacher",
    "src/grade.js~Grade#teacher",
    "member"
  ],
  [
    "src/grade.js~grade#testdate",
    "class/src/grade.js~Grade.html#instance-member-testDate",
    "src/grade.js~Grade#testDate",
    "member"
  ],
  [
    "src/grade.js~grade#type",
    "class/src/grade.js~Grade.html#instance-member-type",
    "src/grade.js~Grade#type",
    "member"
  ],
  [
    "src/grade.js~grade#weight",
    "class/src/grade.js~Grade.html#instance-member-weight",
    "src/grade.js~Grade#weight",
    "member"
  ],
  [
    "src/gradeperiod.js",
    "file/src/gradePeriod.js.html",
    "src/gradePeriod.js",
    "file"
  ],
  [
    "src/gradeperiod.js~gradeperiod#begin",
    "class/src/gradePeriod.js~GradePeriod.html#instance-member-begin",
    "src/gradePeriod.js~GradePeriod#begin",
    "member"
  ],
  [
    "src/gradeperiod.js~gradeperiod#description",
    "class/src/gradePeriod.js~GradePeriod.html#instance-member-description",
    "src/gradePeriod.js~GradePeriod#description",
    "member"
  ],
  [
    "src/gradeperiod.js~gradeperiod#end",
    "class/src/gradePeriod.js~GradePeriod.html#instance-member-end",
    "src/gradePeriod.js~GradePeriod#end",
    "member"
  ],
  [
    "src/gradeperiod.js~gradeperiod#id",
    "class/src/gradePeriod.js~GradePeriod.html#instance-member-id",
    "src/gradePeriod.js~GradePeriod#id",
    "member"
  ],
  [
    "src/gradeperiod.js~gradeperiod#name",
    "class/src/gradePeriod.js~GradePeriod.html#instance-member-name",
    "src/gradePeriod.js~GradePeriod#name",
    "member"
  ],
  [
    "src/gradetype.js",
    "file/src/gradeType.js.html",
    "src/gradeType.js",
    "file"
  ],
  [
    "src/gradetype.js~gradetype#description",
    "class/src/gradeType.js~GradeType.html#instance-member-description",
    "src/gradeType.js~GradeType#description",
    "member"
  ],
  [
    "src/gradetype.js~gradetype#hasnestedtypes",
    "class/src/gradeType.js~GradeType.html#instance-member-hasNestedTypes",
    "src/gradeType.js~GradeType#hasNestedTypes",
    "member"
  ],
  [
    "src/gradetype.js~gradetype#header",
    "class/src/gradeType.js~GradeType.html#instance-member-header",
    "src/gradeType.js~GradeType#header",
    "member"
  ],
  [
    "src/gradetype.js~gradetype#id",
    "class/src/gradeType.js~GradeType.html#instance-member-id",
    "src/gradeType.js~GradeType#id",
    "member"
  ],
  [
    "src/gradetype.js~gradetype#isatlaterdate",
    "class/src/gradeType.js~GradeType.html#instance-member-isAtLaterDate",
    "src/gradeType.js~GradeType#isAtLaterDate",
    "member"
  ],
  [
    "src/gradetype.js~gradetype#ispta",
    "class/src/gradeType.js~GradeType.html#instance-member-isPTA",
    "src/gradeType.js~GradeType#isPTA",
    "member"
  ],
  [
    "src/gradetype.js~gradetype#isteacher",
    "class/src/gradeType.js~GradeType.html#instance-member-isTeacher",
    "src/gradeType.js~GradeType#isTeacher",
    "member"
  ],
  [
    "src/gradetype.js~gradetype#level",
    "class/src/gradeType.js~GradeType.html#instance-member-level",
    "src/gradeType.js~GradeType#level",
    "member"
  ],
  [
    "src/gradetype.js~gradetype#name",
    "class/src/gradeType.js~GradeType.html#instance-member-name",
    "src/gradeType.js~GradeType#name",
    "member"
  ],
  [
    "src/gradetype.js~gradetype#number",
    "class/src/gradeType.js~GradeType.html#instance-member-number",
    "src/gradeType.js~GradeType#number",
    "member"
  ],
  [
    "src/gradetype.js~gradetype#type",
    "class/src/gradeType.js~GradeType.html#instance-get-type",
    "src/gradeType.js~GradeType#type",
    "member"
  ],
  [
    "src/http.js",
    "file/src/http.js.html",
    "src/http.js",
    "file"
  ],
  [
    "src/magister.js",
    "file/src/magister.js.html",
    "src/magister.js",
    "file"
  ],
  [
    "src/magister.js~magister#activities",
    "class/src/magister.js~Magister.html#instance-method-activities",
    "src/magister.js~Magister#activities",
    "method"
  ],
  [
    "src/magister.js~magister#appointments",
    "class/src/magister.js~Magister.html#instance-method-appointments",
    "src/magister.js~Magister#appointments",
    "method"
  ],
  [
    "src/magister.js~magister#assignments",
    "class/src/magister.js~Magister.html#instance-method-assignments",
    "src/magister.js~Magister#assignments",
    "method"
  ],
  [
    "src/magister.js~magister#children",
    "class/src/magister.js~Magister.html#instance-method-children",
    "src/magister.js~Magister#children",
    "method"
  ],
  [
    "src/magister.js~magister#courses",
    "class/src/magister.js~Magister.html#instance-method-courses",
    "src/magister.js~Magister#courses",
    "method"
  ],
  [
    "src/magister.js~magister#createappointment",
    "class/src/magister.js~Magister.html#instance-method-createAppointment",
    "src/magister.js~Magister#createAppointment",
    "method"
  ],
  [
    "src/magister.js~magister#filefolders",
    "class/src/magister.js~Magister.html#instance-method-fileFolders",
    "src/magister.js~Magister#fileFolders",
    "method"
  ],
  [
    "src/magister.js~magister#http",
    "class/src/magister.js~Magister.html#instance-member-http",
    "src/magister.js~Magister#http",
    "member"
  ],
  [
    "src/magister.js~magister#login",
    "class/src/magister.js~Magister.html#instance-method-login",
    "src/magister.js~Magister#login",
    "method"
  ],
  [
    "src/magister.js~magister#messagefolders",
    "class/src/magister.js~Magister.html#instance-method-messageFolders",
    "src/magister.js~Magister#messageFolders",
    "method"
  ],
  [
    "src/magister.js~magister#persons",
    "class/src/magister.js~Magister.html#instance-method-persons",
    "src/magister.js~Magister#persons",
    "method"
  ],
  [
    "src/magister.js~magister#profileinfo",
    "class/src/magister.js~Magister.html#instance-member-profileInfo",
    "src/magister.js~Magister#profileInfo",
    "member"
  ],
  [
    "src/magister.js~magister#school",
    "class/src/magister.js~Magister.html#instance-member-school",
    "src/magister.js~Magister#school",
    "member"
  ],
  [
    "src/magister.js~magister#schoolutilities",
    "class/src/magister.js~Magister.html#instance-method-schoolUtilities",
    "src/magister.js~Magister#schoolUtilities",
    "method"
  ],
  [
    "src/magistererror.js",
    "file/src/magisterError.js.html",
    "src/magisterError.js",
    "file"
  ],
  [
    "src/magistererror.js~magistererror#tostring",
    "class/src/magisterError.js~MagisterError.html#instance-method-toString",
    "src/magisterError.js~MagisterError#toString",
    "method"
  ],
  [
    "src/magisterthing.js",
    "file/src/magisterThing.js.html",
    "src/magisterThing.js",
    "file"
  ],
  [
    "src/message.js",
    "file/src/message.js.html",
    "src/message.js",
    "file"
  ],
  [
    "src/message.js~message#addrecipient",
    "class/src/message.js~Message.html#instance-method-addRecipient",
    "src/message.js~Message#addRecipient",
    "method"
  ],
  [
    "src/message.js~message#attachments",
    "class/src/message.js~Message.html#instance-member-attachments",
    "src/message.js~Message#attachments",
    "member"
  ],
  [
    "src/message.js~message#begin",
    "class/src/message.js~Message.html#instance-member-begin",
    "src/message.js~Message#begin",
    "member"
  ],
  [
    "src/message.js~message#body",
    "class/src/message.js~Message.html#instance-member-body",
    "src/message.js~Message#body",
    "member"
  ],
  [
    "src/message.js~message#constructor",
    "class/src/message.js~Message.html#instance-constructor-constructor",
    "src/message.js~Message#constructor",
    "method"
  ],
  [
    "src/message.js~message#createforwardmessage",
    "class/src/message.js~Message.html#instance-method-createForwardMessage",
    "src/message.js~Message#createForwardMessage",
    "method"
  ],
  [
    "src/message.js~message#createreplymessage",
    "class/src/message.js~Message.html#instance-method-createReplyMessage",
    "src/message.js~Message#createReplyMessage",
    "method"
  ],
  [
    "src/message.js~message#createreplytoallmessage",
    "class/src/message.js~Message.html#instance-method-createReplyToAllMessage",
    "src/message.js~Message#createReplyToAllMessage",
    "method"
  ],
  [
    "src/message.js~message#end",
    "class/src/message.js~Message.html#instance-member-end",
    "src/message.js~Message#end",
    "member"
  ],
  [
    "src/message.js~message#fill",
    "class/src/message.js~Message.html#instance-method-fill",
    "src/message.js~Message#fill",
    "method"
  ],
  [
    "src/message.js~message#folderid",
    "class/src/message.js~Message.html#instance-member-folderId",
    "src/message.js~Message#folderId",
    "member"
  ],
  [
    "src/message.js~message#id",
    "class/src/message.js~Message.html#instance-member-id",
    "src/message.js~Message#id",
    "member"
  ],
  [
    "src/message.js~message#isflagged",
    "class/src/message.js~Message.html#instance-member-isFlagged",
    "src/message.js~Message#isFlagged",
    "member"
  ],
  [
    "src/message.js~message#isread",
    "class/src/message.js~Message.html#instance-member-isRead",
    "src/message.js~Message#isRead",
    "member"
  ],
  [
    "src/message.js~message#move",
    "class/src/message.js~Message.html#instance-method-move",
    "src/message.js~Message#move",
    "method"
  ],
  [
    "src/message.js~message#recipients",
    "class/src/message.js~Message.html#instance-member-recipients",
    "src/message.js~Message#recipients",
    "member"
  ],
  [
    "src/message.js~message#remove",
    "class/src/message.js~Message.html#instance-method-remove",
    "src/message.js~Message#remove",
    "method"
  ],
  [
    "src/message.js~message#savechanges",
    "class/src/message.js~Message.html#instance-method-saveChanges",
    "src/message.js~Message#saveChanges",
    "method"
  ],
  [
    "src/message.js~message#send",
    "class/src/message.js~Message.html#instance-method-send",
    "src/message.js~Message#send",
    "method"
  ],
  [
    "src/message.js~message#senddate",
    "class/src/message.js~Message.html#instance-member-sendDate",
    "src/message.js~Message#sendDate",
    "member"
  ],
  [
    "src/message.js~message#sender",
    "class/src/message.js~Message.html#instance-member-sender",
    "src/message.js~Message#sender",
    "member"
  ],
  [
    "src/message.js~message#state",
    "class/src/message.js~Message.html#instance-member-state",
    "src/message.js~Message#state",
    "member"
  ],
  [
    "src/message.js~message#subject",
    "class/src/message.js~Message.html#instance-member-subject",
    "src/message.js~Message#subject",
    "member"
  ],
  [
    "src/message.js~message#summary",
    "class/src/message.js~Message.html#instance-member-summary",
    "src/message.js~Message#summary",
    "member"
  ],
  [
    "src/message.js~message#tostring",
    "class/src/message.js~Message.html#instance-method-toString",
    "src/message.js~Message#toString",
    "method"
  ],
  [
    "src/message.js~message#type",
    "class/src/message.js~Message.html#instance-get-type",
    "src/message.js~Message#type",
    "member"
  ],
  [
    "src/messagefolder.js",
    "file/src/messageFolder.js.html",
    "src/messageFolder.js",
    "file"
  ],
  [
    "src/messagefolder.js~messagefolder#id",
    "class/src/messageFolder.js~MessageFolder.html#instance-member-id",
    "src/messageFolder.js~MessageFolder#id",
    "member"
  ],
  [
    "src/messagefolder.js~messagefolder#messages",
    "class/src/messageFolder.js~MessageFolder.html#instance-method-messages",
    "src/messageFolder.js~MessageFolder#messages",
    "method"
  ],
  [
    "src/messagefolder.js~messagefolder#name",
    "class/src/messageFolder.js~MessageFolder.html#instance-member-name",
    "src/messageFolder.js~MessageFolder#name",
    "member"
  ],
  [
    "src/messagefolder.js~messagefolder#parentid",
    "class/src/messageFolder.js~MessageFolder.html#instance-member-parentId",
    "src/messageFolder.js~MessageFolder#parentId",
    "member"
  ],
  [
    "src/messagefolder.js~messagefolder#tojson",
    "class/src/messageFolder.js~MessageFolder.html#instance-method-toJSON",
    "src/messageFolder.js~MessageFolder#toJSON",
    "method"
  ],
  [
    "src/messagefolder.js~messagefolder#type",
    "class/src/messageFolder.js~MessageFolder.html#instance-member-type",
    "src/messageFolder.js~MessageFolder#type",
    "member"
  ],
  [
    "src/messagefolder.js~messagefolder#unreadcount",
    "class/src/messageFolder.js~MessageFolder.html#instance-member-unreadCount",
    "src/messageFolder.js~MessageFolder#unreadCount",
    "member"
  ],
  [
    "src/person.js",
    "file/src/person.js.html",
    "src/person.js",
    "file"
  ],
  [
    "src/person.js~person#description",
    "class/src/person.js~Person.html#instance-member-description",
    "src/person.js~Person#description",
    "member"
  ],
  [
    "src/person.js~person#emailaddress",
    "class/src/person.js~Person.html#instance-member-emailAddress",
    "src/person.js~Person#emailAddress",
    "member"
  ],
  [
    "src/person.js~person#firstname",
    "class/src/person.js~Person.html#instance-member-firstName",
    "src/person.js~Person#firstName",
    "member"
  ],
  [
    "src/person.js~person#fullname",
    "class/src/person.js~Person.html#instance-member-fullName",
    "src/person.js~Person#fullName",
    "member"
  ],
  [
    "src/person.js~person#getfilled",
    "class/src/person.js~Person.html#instance-method-getFilled",
    "src/person.js~Person#getFilled",
    "method"
  ],
  [
    "src/person.js~person#group",
    "class/src/person.js~Person.html#instance-member-group",
    "src/person.js~Person#group",
    "member"
  ],
  [
    "src/person.js~person#id",
    "class/src/person.js~Person.html#instance-member-id",
    "src/person.js~Person#id",
    "member"
  ],
  [
    "src/person.js~person#lastname",
    "class/src/person.js~Person.html#instance-member-lastName",
    "src/person.js~Person#lastName",
    "member"
  ],
  [
    "src/person.js~person#nameprefix",
    "class/src/person.js~Person.html#instance-member-namePrefix",
    "src/person.js~Person#namePrefix",
    "member"
  ],
  [
    "src/person.js~person#teachercode",
    "class/src/person.js~Person.html#instance-member-teacherCode",
    "src/person.js~Person#teacherCode",
    "member"
  ],
  [
    "src/person.js~person#tojson",
    "class/src/person.js~Person.html#instance-method-toJSON",
    "src/person.js~Person#toJSON",
    "method"
  ],
  [
    "src/person.js~person#type",
    "class/src/person.js~Person.html#instance-get-type",
    "src/person.js~Person#type",
    "member"
  ],
  [
    "src/person.js~person#type",
    "class/src/person.js~Person.html#instance-set-type",
    "src/person.js~Person#type",
    "member"
  ],
  [
    "src/privileges.js",
    "file/src/privileges.js.html",
    "src/privileges.js",
    "file"
  ],
  [
    "src/profileinfo.js",
    "file/src/profileInfo.js.html",
    "src/profileInfo.js",
    "file"
  ],
  [
    "src/profileinfo.js~profileinfo#address",
    "class/src/profileInfo.js~ProfileInfo.html#instance-method-address",
    "src/profileInfo.js~ProfileInfo#address",
    "method"
  ],
  [
    "src/profileinfo.js~profileinfo#birthdate",
    "class/src/profileInfo.js~ProfileInfo.html#instance-member-birthDate",
    "src/profileInfo.js~ProfileInfo#birthDate",
    "member"
  ],
  [
    "src/profileinfo.js~profileinfo#birthnameprefix",
    "class/src/profileInfo.js~ProfileInfo.html#instance-member-birthNamePrefix",
    "src/profileInfo.js~ProfileInfo#birthNamePrefix",
    "member"
  ],
  [
    "src/profileinfo.js~profileinfo#birthsurname",
    "class/src/profileInfo.js~ProfileInfo.html#instance-member-birthSurname",
    "src/profileInfo.js~ProfileInfo#birthSurname",
    "member"
  ],
  [
    "src/profileinfo.js~profileinfo#firstname",
    "class/src/profileInfo.js~ProfileInfo.html#instance-member-firstName",
    "src/profileInfo.js~ProfileInfo#firstName",
    "member"
  ],
  [
    "src/profileinfo.js~profileinfo#getfullname",
    "class/src/profileInfo.js~ProfileInfo.html#instance-method-getFullName",
    "src/profileInfo.js~ProfileInfo#getFullName",
    "method"
  ],
  [
    "src/profileinfo.js~profileinfo#getprofilepicture",
    "class/src/profileInfo.js~ProfileInfo.html#instance-method-getProfilePicture",
    "src/profileInfo.js~ProfileInfo#getProfilePicture",
    "method"
  ],
  [
    "src/profileinfo.js~profileinfo#id",
    "class/src/profileInfo.js~ProfileInfo.html#instance-member-id",
    "src/profileInfo.js~ProfileInfo#id",
    "member"
  ],
  [
    "src/profileinfo.js~profileinfo#initials",
    "class/src/profileInfo.js~ProfileInfo.html#instance-member-initials",
    "src/profileInfo.js~ProfileInfo#initials",
    "member"
  ],
  [
    "src/profileinfo.js~profileinfo#ischild",
    "class/src/profileInfo.js~ProfileInfo.html#instance-member-isChild",
    "src/profileInfo.js~ProfileInfo#isChild",
    "member"
  ],
  [
    "src/profileinfo.js~profileinfo#isvisibleforparent",
    "class/src/profileInfo.js~ProfileInfo.html#instance-member-isVisibleForParent",
    "src/profileInfo.js~ProfileInfo#isVisibleForParent",
    "member"
  ],
  [
    "src/profileinfo.js~profileinfo#lastname",
    "class/src/profileInfo.js~ProfileInfo.html#instance-member-lastName",
    "src/profileInfo.js~ProfileInfo#lastName",
    "member"
  ],
  [
    "src/profileinfo.js~profileinfo#nameprefix",
    "class/src/profileInfo.js~ProfileInfo.html#instance-member-namePrefix",
    "src/profileInfo.js~ProfileInfo#namePrefix",
    "member"
  ],
  [
    "src/profileinfo.js~profileinfo#officialfirstnames",
    "class/src/profileInfo.js~ProfileInfo.html#instance-member-officialFirstNames",
    "src/profileInfo.js~ProfileInfo#officialFirstNames",
    "member"
  ],
  [
    "src/profileinfo.js~profileinfo#officialsurname",
    "class/src/profileInfo.js~ProfileInfo.html#instance-member-officialSurname",
    "src/profileInfo.js~ProfileInfo#officialSurname",
    "member"
  ],
  [
    "src/profileinfo.js~profileinfo#settings",
    "class/src/profileInfo.js~ProfileInfo.html#instance-method-settings",
    "src/profileInfo.js~ProfileInfo#settings",
    "method"
  ],
  [
    "src/profileinfo.js~profileinfo#usebirthname",
    "class/src/profileInfo.js~ProfileInfo.html#instance-member-useBirthname",
    "src/profileInfo.js~ProfileInfo#useBirthname",
    "member"
  ],
  [
    "src/profilesettings.js",
    "file/src/profileSettings.js.html",
    "src/profileSettings.js",
    "file"
  ],
  [
    "src/profilesettings.js~profilesettings#changepassword",
    "class/src/profileSettings.js~ProfileSettings.html#instance-method-changePassword",
    "src/profileSettings.js~ProfileSettings#changePassword",
    "method"
  ],
  [
    "src/profilesettings.js~profilesettings#emailaddress",
    "class/src/profileSettings.js~ProfileSettings.html#instance-member-emailAddress",
    "src/profileSettings.js~ProfileSettings#emailAddress",
    "member"
  ],
  [
    "src/profilesettings.js~profilesettings#mobilenumber",
    "class/src/profileSettings.js~ProfileSettings.html#instance-member-mobileNumber",
    "src/profileSettings.js~ProfileSettings#mobileNumber",
    "member"
  ],
  [
    "src/profilesettings.js~profilesettings#redirectmagistermessages",
    "class/src/profileSettings.js~ProfileSettings.html#instance-member-redirectMagisterMessages",
    "src/profileSettings.js~ProfileSettings#redirectMagisterMessages",
    "member"
  ],
  [
    "src/profilesettings.js~profilesettings#savechanges",
    "class/src/profileSettings.js~ProfileSettings.html#instance-method-saveChanges",
    "src/profileSettings.js~ProfileSettings#saveChanges",
    "method"
  ],
  [
    "src/school.js",
    "file/src/school.js.html",
    "src/school.js",
    "file"
  ],
  [
    "src/school.js~school#id",
    "class/src/school.js~School.html#instance-member-id",
    "src/school.js~School#id",
    "member"
  ],
  [
    "src/school.js~school#name",
    "class/src/school.js~School.html#instance-member-name",
    "src/school.js~School#name",
    "member"
  ],
  [
    "src/school.js~school#url",
    "class/src/school.js~School.html#instance-member-url",
    "src/school.js~School#url",
    "member"
  ],
  [
    "src/school.js~school#versioninfo",
    "class/src/school.js~School.html#instance-method-versionInfo",
    "src/school.js~School#versionInfo",
    "method"
  ],
  [
    "src/schoolutility.js",
    "file/src/schoolUtility.js.html",
    "src/schoolUtility.js",
    "file"
  ],
  [
    "src/schoolutility.js~schoolutility#ean",
    "class/src/schoolUtility.js~SchoolUtility.html#instance-member-EAN",
    "src/schoolUtility.js~SchoolUtility#EAN",
    "member"
  ],
  [
    "src/schoolutility.js~schoolutility#begin",
    "class/src/schoolUtility.js~SchoolUtility.html#instance-member-begin",
    "src/schoolUtility.js~SchoolUtility#begin",
    "member"
  ],
  [
    "src/schoolutility.js~schoolutility#class",
    "class/src/schoolUtility.js~SchoolUtility.html#instance-member-class",
    "src/schoolUtility.js~SchoolUtility#class",
    "member"
  ],
  [
    "src/schoolutility.js~schoolutility#end",
    "class/src/schoolUtility.js~SchoolUtility.html#instance-member-end",
    "src/schoolUtility.js~SchoolUtility#end",
    "member"
  ],
  [
    "src/schoolutility.js~schoolutility#id",
    "class/src/schoolUtility.js~SchoolUtility.html#instance-member-id",
    "src/schoolUtility.js~SchoolUtility#id",
    "member"
  ],
  [
    "src/schoolutility.js~schoolutility#name",
    "class/src/schoolUtility.js~SchoolUtility.html#instance-member-name",
    "src/schoolUtility.js~SchoolUtility#name",
    "member"
  ],
  [
    "src/schoolutility.js~schoolutility#publisher",
    "class/src/schoolUtility.js~SchoolUtility.html#instance-member-publisher",
    "src/schoolUtility.js~SchoolUtility#publisher",
    "member"
  ],
  [
    "src/schoolutility.js~schoolutility#state",
    "class/src/schoolUtility.js~SchoolUtility.html#instance-member-state",
    "src/schoolUtility.js~SchoolUtility#state",
    "member"
  ],
  [
    "src/schoolutility.js~schoolutility#type",
    "class/src/schoolUtility.js~SchoolUtility.html#instance-member-type",
    "src/schoolUtility.js~SchoolUtility#type",
    "member"
  ],
  [
    "src/schoolutility.js~schoolutility#url",
    "class/src/schoolUtility.js~SchoolUtility.html#instance-member-url",
    "src/schoolUtility.js~SchoolUtility#url",
    "member"
  ],
  [
    "src/util.js",
    "file/src/util.js.html",
    "src/util.js",
    "file"
  ],
  [
    "src/versioninfo.js",
    "file/src/versionInfo.js.html",
    "src/versionInfo.js",
    "file"
  ],
  [
    "src/versioninfo.js~versioninfo#api",
    "class/src/versionInfo.js~VersionInfo.html#instance-member-api",
    "src/versionInfo.js~VersionInfo#api",
    "member"
  ],
  [
    "src/versioninfo.js~versioninfo#core",
    "class/src/versionInfo.js~VersionInfo.html#instance-member-core",
    "src/versionInfo.js~VersionInfo#core",
    "member"
  ],
  [
    "src/versioninfo.js~versioninfo#db",
    "class/src/versionInfo.js~VersionInfo.html#instance-member-db",
    "src/versionInfo.js~VersionInfo#db",
    "member"
  ],
  [
    "src/versioninfo.js~versioninfo#product",
    "class/src/versionInfo.js~VersionInfo.html#instance-member-product",
    "src/versionInfo.js~VersionInfo#product",
    "member"
  ],
  [
    "src/versioninfo.js~versioninfo#releasedon",
    "class/src/versionInfo.js~VersionInfo.html#instance-member-releasedOn",
    "src/versionInfo.js~VersionInfo#releasedOn",
    "member"
  ]
]